/* eslint-disable max-len,global-require */
import { FurnitureType, IFurniture } from '@root/Shared/types/furniture';

export const furnitureData: IFurniture[] = [
  {
    id: '1',
    src: require('@root/Shared/assets/images/luna-recliner.png'),
    title: 'Luna Recliner',
    description: 'A modern recliner with soft upholstery, designed for ultimate relaxation.',
    price: 290,
    rating: 4.7,
    type: FurnitureType.UpholsteredChair,
  },
  {
    id: '2',
    src: require('@root/Shared/assets/images/astra-chair.png'),
    title: 'Astra Chair',
    description: 'A modern minimalist chair with sleek metal accents, perfect for contemporary interiors.',
    price: 311,
    rating: 4.1,
    type: FurnitureType.UpholsteredChair,
  },
  {
    id: '3',
    src: require('@root/Shared/assets/images/comfy-nest-lounge.png'),
    title: 'ComfyNest Lounge',
    description: 'A spacious lounge chair with extra padding and fabric upholstery for added comfort.',
    price: 393,
    rating: 4.5,
    type: FurnitureType.UpholsteredChair,
  },
  {
    id: '4',
    src: require('@root/Shared/assets/images/elegant-armchair.png'),
    title: 'Elegant Armchair',
    description: 'A classic armchair featuring wooden armrests and a timeless design for refined spaces.',
    price: 435,
    rating: 4.6,
    type: FurnitureType.UpholsteredChair,
  },
  {
    id: '5',
    src: require('@root/Shared/assets/images/pixel-gaming-chair.png'),
    title: 'Pixel Gaming Chair',
    description: 'A gaming chair with adjustable seating and ergonomic design, tailored for an immersive experience.',
    price: 225,
    rating: 4.3,
    type: FurnitureType.UpholsteredChair,
  },
  {
    id: '6',
    src: require('@root/Shared/assets/images/skyline-executive.png'),
    title: 'Skyline Executive',
    description: 'A premium office chair with luxurious leather upholstery and a high backrest for maximum comfort.',
    price: 400,
    rating: 4.8,
    type: FurnitureType.UpholsteredChair,
  },
  {
    id: '7',
    src: require('@root/Shared/assets/images/cloud-soft-sofa.png'),
    title: 'CloudSoft Sofa',
    description: 'A plush sofa with fully upholstery, designed for maximum comfort and a cozy living room.',
    price: 624,
    rating: 4.0,
    type: FurnitureType.ComfortableSofa,
  },
  {
    id: '8',
    src: require('@root/Shared/assets/images/urban-modular.png'),
    title: 'UrbanModular',
    description: 'A modular sofa with a minimalist design, ideal for modern interiors and versatile spaces.',
    price: 876,
    rating: 4.3,
    type: FurnitureType.ComfortableSofa,
  },
  {
    id: '9',
    src: require('@root/Shared/assets/images/royal-chesterfield.png'),
    title: 'Royal Chesterfield',
    description: 'A classic Chesterfield sofa with luxurious leather upholstery and a tufted design for timeless elegance.',
    price: 1133,
    rating: 4.4,
    type: FurnitureType.ComfortableSofa,
  },
  {
    id: '10',
    src: require('@root/Shared/assets/images/luxe-recliner-sofa.png'),
    title: 'Luxe Recliner Sofa',
    description: 'A reclining sofa with plush cushions and retractable footrests for ultimate relaxation in the modern look.',
    price: 1236,
    rating: 4.6,
    type: FurnitureType.ComfortableSofa,
  },
  {
    id: '11',
    src: require('@root/Shared/assets/images/scandi-comfort.png'),
    title: 'ScandiComfort',
    description: 'A Scandinavian-style sofa with wooden armrests, soft fabrics, and a clean and timeless design.',
    price: 535,
    rating: 4.5,
    type: FurnitureType.ComfortableSofa,
  },
  {
    id: '12',
    src: require('@root/Shared/assets/images/family-lounge.png'),
    title: 'Family Lounge',
    description: 'A spacious sofa with durable fabric upholstery, perfect for accommodating the entire family.',
    price: 1000,
    rating: 4.7,
    type: FurnitureType.ComfortableSofa,
  },
];
